# Generated by Django 4.0.4 on 2022-05-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_closed_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closed_listing',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_listings', to='auctions.listing'),
        ),
    ]
