# Generated by Django 4.0.4 on 2022-05-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_closed_listing_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closed_listing',
            name='listing',
        ),
        migrations.AddField(
            model_name='closed_listing',
            name='last_bid_user',
            field=models.CharField(default='teste', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closed_listing',
            name='title',
            field=models.CharField(default='teste', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closed_listing',
            name='user_who_created',
            field=models.CharField(default='teste', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closed_listing',
            name='value',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
